env:
    - GO111MODULE=on
    - CGO_ENABLED=0
before:
    hooks:
        - go mod tidy
        - go mod download
builds:
    - binary: dp
      env:
          - CGO_ENABLED=1
          - GO111MODULE=on
          - CC=o64-clang
          - CXX=o64-clang++
      main: ./desk.go
      goos:
          - darwin
      goarch:
          - amd64
      ignore:
          - goos: darwin
            goarch: 386
archives:
    - format: tar.gz
      format_overrides:
          - goos: windows
            format: zip
      name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
      replacements:
          amd64: 64bit
          386: 32bit
          arm: ARM
          arm64: ARM64
          darwin: macOS
          linux: Linux
          windows: Windows
          openbsd: OpenBSD
          netbsd: NetBSD
          freebsd: FreeBSD
          dragonfly: DragonFlyBSD
      files:
          - Readme.md
          - LICENSE
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: '{{ .Tag }}-next'
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
            - 'README'
            - Merge pull request
            - Merge branch